##
## EPITECH PROJECT, 2023
## B-OOP-400-MLH-4-1-raytracer-theotime.schmeltz
## File description:
## Makefile
##

all :
	make -C Sphere
	make -C Planes
	make -C Cylinder
	make -C Cone

clean :
	make clean -C Sphere
	make clean -C Planes
	make clean -C Cylinder
	make clean -C Cone

re :
	make re -C Sphere
	make re -C Planes
	make re -C Cone
