##
## EPITECH PROJECT, 2022
## B-OOP-400-MLH-4-1-raytracer-theotime.schmeltz
## File description:
## Makefile
##

all :
	make -C Directional
	make -C Ambient

clean :
	make clean -C Directional
	make clean -C Ambient

re :
	make re -C Directional
	make re -C Ambient
